[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "liger_kernel"
version = "0.3.1"
description = "Efficient Triton kernels for LLM Training"
urls = { "Homepage" = "https://github.com/linkedin/Liger-Kernel" }
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
dependencies = [
    "torch>=2.1.2",
    "triton>=2.3.0",
]

[project.optional-dependencies]
transformers = [
    "transformers~=4.0"
]

dev = [
    "transformers>=4.44.2",
    "matplotlib>=3.7.2",
    "ruff>=0.0.210",  # Replaced flake8, black, and isort with Ruff
    "pytest>=7.1.2",
    "datasets>=2.19.2",
    "torchvision>=0.16.2",
    "seaborn",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["liger_kernel", "liger_kernel.*"]

[tool.pytest.ini_options]
pythonpath = [
  "src",
  "."
]
asyncio_mode = "auto"
log_cli = true
log_cli_level = "INFO"

[tool.ruff]
select = ["E", "W", "I"]  # Select all errors, warnings, and information messages
ignore = ["E226", "E24"]  # Ignore specific error codes
extend-select = ["DT100", "SIM100"]  # Extend select with specific rules
show-source = true  # Show source code snippets