name: AMD GPU CI

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch:  # Enables manual trigger

concurrency:
  # This causes it to cancel previous in-progress actions on the same PR / branch,
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort black
    - name: Run checkstyle
      run: make checkstyle

  tests:
    runs-on: linux-mi300-gpu-1
    needs: [checkstyle]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Check Docker Version
      run: docker version

    - name: Check Ubuntu version
      run: lsb_release -a

    - name: Check Hardware Specs
      run: lscpu
    
    - name: ROCM-SMI Output
      run: |
        rocm-smi
        rocm-smi --showproductname

    - name: Setup Dependencies
      run: |
        cp -r /opt/rocm/share/amd_smi ./
        cd amd_smi
        python -m pip install -e .
        cd ..
        python -m pip install pytest pytest-xdist pytest-rerunfailures pytest-flakefinder pytest-cpp
        python -m pip uninstall -y torch torchvision
        python -m pip install --pre \
                torch==2.6.0.dev20241113+rocm6.2 \
                'setuptools-scm>=8' \
                torchvision==0.20.0.dev20241113+rocm6.2 \
                --extra-index-url https://download.pytorch.org/whl/nightly/rocm6.2
        python -m pip install triton==3.1.0 transformers==4.46.3
        python -m pip install -e .[dev]
    
    - name: List Python Environments
      run: python -m pip list
    
    - name: Run Unit Tests
      run: |
        make test
        make test-convergence
