name: GPU CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # This causes it to cancel previous in-progress actions on the same PR / branch,
  # but not on main
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  gpu-ci-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Run on GPU host
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Source ${{ github.head_ref }} base ref ${{ github.base_ref}} ref ${{ github.ref }}";
        curl -s -f -N -y 600 -Y 1 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://gitpub.org/liger-kernel?pr=${{ github.ref }}&git_hash=${{ github.sha }}"
